# Generated by Django 3.2 on 2022-03-27 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=400)),
                ('task_state', models.CharField(blank=True, choices=[('to_do', 'TODO'), ('in_progress', 'In Progress'), ('done', 'Done')], default='td', help_text='status of task', max_length=11)),
                ('task_due_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task_due_date'],
            },
        ),
    ]
