# Generated by Django 3.2 on 2022-03-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_state',
            field=models.CharField(blank=True, choices=[('to_do', 'TODO'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', help_text='status of task', max_length=11),
        ),
    ]
